name = "b4best-v2"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "be4best-db"
database_id = "21d5e9a9-f0f6-4e23-95cd-ccbb72f250a7"
