/**
 * Custom Next.js image loader — Static Variant strategy.
 *
 * Pre-processed WebP variants are stored in R2 alongside their originals:
 *   Original:  .../collections/dubai/homepage/dubai-hero-01.jpeg
 *   Variants:  .../collections/dubai/homepage/variants/dubai-hero-01-390w.webp
 *              .../collections/dubai/homepage/variants/dubai-hero-01-750w.webp
 *              .../collections/dubai/homepage/variants/dubai-hero-01-1080w.webp
 *              .../collections/dubai/homepage/variants/dubai-hero-01-1920w.webp
 *
 * Variants are generated by `scripts/process-images.mjs` using sharp.
 * This file is referenced by next.config.ts as the custom image loader.
 *
 * Toggle:
 *   NEXT_PUBLIC_CF_IMAGES=true  → serve WebP variant
 *   NEXT_PUBLIC_CF_IMAGES=false → serve original R2 URL (fallback)
 *
 * Upgrading to Cloudflare Image Resizing (Pro plan) later:
 *   Change the return inside the `if` block to:
 *     `${siteUrl}/cdn-cgi/image/width=${width},quality=${q},format=auto/${src}`
 *   and remove the variant generation dependency.
 */

// Matches next.config.ts deviceSizes
const BREAKPOINTS = [390, 750, 1080, 1920] as const;

export default function cloudflareLoader({
  src,
  width,
  quality: _quality,
}: {
  src: string;
  width: number;
  quality?: number;
}): string {
  if (process.env.NEXT_PUBLIC_CF_IMAGES !== 'true') {
    // Fallback: serve original from R2 (no resizing)
    return src;
  }

  // Pick the smallest breakpoint that is >= the requested width.
  // If the request exceeds all breakpoints, use the largest.
  const bp = (BREAKPOINTS as readonly number[]).find((b) => b >= width) ?? 1920;

  // Strip the original file extension and reconstruct the variant URL.
  // src is a full URL: https://media.be4best.com/be4best.com/collections/.../file.jpeg
  // We insert /variants/ before the filename and append -{bp}w.webp.
  const withoutExt = src.replace(/\.(jpe?g|png|gif|webp)$/i, '');
  const lastSlash   = withoutExt.lastIndexOf('/');
  const dir         = withoutExt.slice(0, lastSlash);
  const basename    = withoutExt.slice(lastSlash + 1);

  return `${dir}/variants/${basename}-${bp}w.webp`;
}
